<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Paris, Madrid">
<General productName="Micro Focus UFT One" productVer="2021" os="Windows 10" host="NXQLX302"><DocLocation><![CDATA[C:\robot\test_UFT\JpetStore\JpetStore]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[JpetStore]]></DName>
<Res><![CDATA[Res48]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action principale]]></AName>
<Action rID="T5">
<AName><![CDATA[Affichage [Connexion]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[25/08/2022 - 09:53:44]]></Time>
<TimeTick>1661414024</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Mozilla Firefox\firefox.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Mozilla Firefox\firefox.exe",1]]></Details>
<Time><![CDATA[25/08/2022 - 09:53:44]]></Time>
<TimeTick>1661414024</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" Source="Affichage [Connexion]" SourceLine="21" >
<Disp><![CDATA[Run "C:\Program Files\Mozilla Firefox\firefox.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" Source="Affichage [Connexion]" SourceLine="21" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément image_JpetStore a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:04]]></Time>
<TimeTick>1661414044</TimeTick>
<NodeArgs eType="User" icon="7" nRep="13" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA[Affichage page accueil]]></Obj>
<Details ><![CDATA[La page d'accueil s'est affichée.]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:04]]></Time>
<TimeTick>1661414044</TimeTick>
<NodeArgs eType="User" icon="7" nRep="14" status="Passed" Source="Affichage [Connexion]" SourceLine="26" >
<Disp><![CDATA[Affichage page accueil]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/08/2022 - 09:53:44" eTime="25/08/2022 - 09:54:04" passed="3" failed="0" warnings="0" ><Param paramInOut = "In"><ParamName><![CDATA[browser]]></ParamName><ParamVal><![CDATA[firefox]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Passed" >
<Disp><![CDATA[Récapitulatif Affichage [Connexion]]]></Disp>
</NodeArgs>
</Action>
<Action rID="T10">
<AName><![CDATA[ConnexionClient [Connexion]]]></AName>
<Step rID="T11">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément Sign In a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:24]]></Time>
<TimeTick>1661414064</TimeTick>
<NodeArgs eType="User" icon="7" nRep="17" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[JPetStore]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:24]]></Time>
<TimeTick>1661414064</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Accueil]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:24]]></Time>
<TimeTick>1661414064</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Sign In.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:24]]></Time>
<TimeTick>1661414064</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="21" >
<Disp><![CDATA[Sign In.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="20" >
<Disp><![CDATA[Accueil]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="19" >
<Disp><![CDATA[JPetStore]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj ><![CDATA[CliquerElement]]></Obj>
<Details ><![CDATA[L'élément a été cliqué.]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:24]]></Time>
<TimeTick>1661414064</TimeTick>
<NodeArgs eType="User" icon="7" nRep="22" status="Passed" >
<Disp><![CDATA[CliquerElement]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément text_login a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<NodeArgs eType="User" icon="7" nRep="23" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[Affichage page login]]></Obj>
<Details ><![CDATA[La page login s'est affichée.]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<NodeArgs eType="User" icon="7" nRep="24" status="Passed" Source="ConnexionClient [Connexion]" SourceLine="11" >
<Disp><![CDATA[Affichage page login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément username a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<NodeArgs eType="User" icon="7" nRep="25" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[JPetStore]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[LogIn]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["j2ee"]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="29" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="28" >
<Disp><![CDATA[LogIn]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="27" >
<Disp><![CDATA[JPetStore]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[saisirElement]]></Obj>
<Details ><![CDATA[La chaîne 'j2ee' a été saisie.]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<NodeArgs eType="User" icon="7" nRep="30" status="Passed" >
<Disp><![CDATA[saisirElement]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément password a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<NodeArgs eType="User" icon="7" nRep="31" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[JPetStore]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[LogIn]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["j2ee"]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="35" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="34" >
<Disp><![CDATA[LogIn]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="33" >
<Disp><![CDATA[JPetStore]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[saisirElement]]></Obj>
<Details ><![CDATA[La chaîne 'j2ee' a été saisie.]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<NodeArgs eType="User" icon="7" nRep="36" status="Passed" >
<Disp><![CDATA[saisirElement]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément Login a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<NodeArgs eType="User" icon="7" nRep="37" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[JPetStore]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[LogIn]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="41" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="40" >
<Disp><![CDATA[LogIn]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="39" >
<Disp><![CDATA[JPetStore]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA[CliquerElement]]></Obj>
<Details ><![CDATA[L'élément a été cliqué.]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<NodeArgs eType="User" icon="7" nRep="42" status="Passed" >
<Disp><![CDATA[CliquerElement]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément Sign Out a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<NodeArgs eType="User" icon="7" nRep="43" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[Affichage page accueil]]></Obj>
<Details ><![CDATA[Je suis bien connecté]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:25]]></Time>
<TimeTick>1661414065</TimeTick>
<NodeArgs eType="User" icon="7" nRep="44" status="Passed" Source="ConnexionClient [Connexion]" SourceLine="24" >
<Disp><![CDATA[Affichage page accueil]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/08/2022 - 09:54:04" eTime="25/08/2022 - 09:54:25" passed="12" failed="0" warnings="0" ><Param paramInOut = "In"><ParamName><![CDATA[DS_username]]></ParamName><ParamVal><![CDATA[j2ee]]></ParamVal>
</Param>
<Param paramInOut = "In"><ParamName><![CDATA[DS_password]]></ParamName><ParamVal><![CDATA[j2ee]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="5" nRep="16" status="Passed" >
<Disp><![CDATA[Récapitulatif ConnexionClient [Connexion]]]></Disp>
</NodeArgs>
</Action>
<Action rID="T35">
<AName><![CDATA[PageAccueil [SelectionArticle]]]></AName>
<Step rID="T36">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément fish_icon a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:45]]></Time>
<TimeTick>1661414085</TimeTick>
<NodeArgs eType="User" icon="7" nRep="47" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[JPetStore]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:45]]></Time>
<TimeTick>1661414085</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Accueil]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:45]]></Time>
<TimeTick>1661414085</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[fish_icon.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:45]]></Time>
<TimeTick>1661414085</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="51" >
<Disp><![CDATA[fish_icon.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="50" >
<Disp><![CDATA[Accueil]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="49" >
<Disp><![CDATA[JPetStore]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj ><![CDATA[CliquerElement]]></Obj>
<Details ><![CDATA[L'élément a été cliqué.]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:45]]></Time>
<TimeTick>1661414085</TimeTick>
<NodeArgs eType="User" icon="7" nRep="52" status="Passed" >
<Disp><![CDATA[CliquerElement]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément Fish a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:46]]></Time>
<TimeTick>1661414086</TimeTick>
<NodeArgs eType="User" icon="7" nRep="53" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA[Affichage page Fish]]></Obj>
<Details ><![CDATA[La page produit Fish s'est affichée.]]></Details>
<Time><![CDATA[25/08/2022 - 09:54:46]]></Time>
<TimeTick>1661414086</TimeTick>
<NodeArgs eType="User" icon="7" nRep="54" status="Passed" Source="PageAccueil [SelectionArticle]" SourceLine="9" >
<Disp><![CDATA[Affichage page Fish]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/08/2022 - 09:54:25" eTime="25/08/2022 - 09:54:46" passed="4" failed="0" warnings="0" ><Param paramInOut = "In"><ParamName><![CDATA[taille]]></ParamName><ParamVal><![CDATA[]]></ParamVal>
</Param>
<Param paramInOut = "In"><ParamName><![CDATA[couleur]]></ParamName><ParamVal><![CDATA[]]></ParamVal>
</Param>
<Param paramInOut = "In"><ParamName><![CDATA[quantite]]></ParamName><ParamVal><![CDATA[]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="5" nRep="46" status="Passed" >
<Disp><![CDATA[Récapitulatif PageAccueil [SelectionArticle]]]></Disp>
</NodeArgs>
</Action>
<Action rID="T43">
<AName><![CDATA[PageCatégorie [SelectionArticle]]]></AName>
<Step rID="T44">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément FI-SW-01 a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:06]]></Time>
<TimeTick>1661414106</TimeTick>
<NodeArgs eType="User" icon="7" nRep="57" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[JPetStore]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:06]]></Time>
<TimeTick>1661414106</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Produit]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:06]]></Time>
<TimeTick>1661414106</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[FI-SW-01.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:06]]></Time>
<TimeTick>1661414106</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="61" >
<Disp><![CDATA[FI-SW-01.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="60" >
<Disp><![CDATA[Produit]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="59" >
<Disp><![CDATA[JPetStore]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[CliquerElement]]></Obj>
<Details ><![CDATA[L'élément a été cliqué.]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:06]]></Time>
<TimeTick>1661414106</TimeTick>
<NodeArgs eType="User" icon="7" nRep="62" status="Passed" >
<Disp><![CDATA[CliquerElement]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément Angelfish a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:06]]></Time>
<TimeTick>1661414106</TimeTick>
<NodeArgs eType="User" icon="7" nRep="63" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj ><![CDATA[Affichage page AngelFish]]></Obj>
<Details ><![CDATA[La page produit AngelFish s'est affichée.]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:06]]></Time>
<TimeTick>1661414106</TimeTick>
<NodeArgs eType="User" icon="7" nRep="64" status="Passed" Source="PageCatégorie [SelectionArticle]" SourceLine="9" >
<Disp><![CDATA[Affichage page AngelFish]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément Add to Cart a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:06]]></Time>
<TimeTick>1661414106</TimeTick>
<NodeArgs eType="User" icon="7" nRep="65" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[JPetStore]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:06]]></Time>
<TimeTick>1661414106</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[AngelFish]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:06]]></Time>
<TimeTick>1661414106</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Add to Cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:06]]></Time>
<TimeTick>1661414106</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="69" >
<Disp><![CDATA[Add to Cart.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="68" >
<Disp><![CDATA[AngelFish]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="67" >
<Disp><![CDATA[JPetStore]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj ><![CDATA[CliquerElement]]></Obj>
<Details ><![CDATA[L'élément a été cliqué.]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:06]]></Time>
<TimeTick>1661414106</TimeTick>
<NodeArgs eType="User" icon="7" nRep="70" status="Passed" >
<Disp><![CDATA[CliquerElement]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément Shopping Cart a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:06]]></Time>
<TimeTick>1661414106</TimeTick>
<NodeArgs eType="User" icon="7" nRep="71" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj ><![CDATA[Affichage page Shopping Cart]]></Obj>
<Details ><![CDATA[La page Shopping Cart s'est affichée.]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:06]]></Time>
<TimeTick>1661414106</TimeTick>
<NodeArgs eType="User" icon="7" nRep="72" status="Passed" Source="PageCatégorie [SelectionArticle]" SourceLine="17" >
<Disp><![CDATA[Affichage page Shopping Cart]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/08/2022 - 09:54:46" eTime="25/08/2022 - 09:55:06" passed="8" failed="0" warnings="0" ><Param paramInOut = "In"><ParamName><![CDATA[Message]]></ParamName><ParamVal><![CDATA[Squash est awesome!]]></ParamVal>
</Param>
<Param paramInOut = "In"><ParamName><![CDATA[Quantite]]></ParamName><ParamVal><![CDATA[0]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="5" nRep="56" status="Passed" >
<Disp><![CDATA[Récapitulatif PageCatégorie [SelectionArticle]]]></Disp>
</NodeArgs>
</Action>
<Action rID="T58">
<AName><![CDATA[PageCart [SelectionArticle]]]></AName>
<Step rID="T59">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément EST-1 a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<NodeArgs eType="User" icon="7" nRep="75" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[JPetStore]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[ShoppingCart]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[EST-1.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="79" >
<Disp><![CDATA[EST-1.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="78" >
<Disp><![CDATA[ShoppingCart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="77" >
<Disp><![CDATA[JPetStore]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj ><![CDATA[CliquerElement]]></Obj>
<Details ><![CDATA[L'élément a été cliqué.]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<NodeArgs eType="User" icon="7" nRep="80" status="Passed" >
<Disp><![CDATA[CliquerElement]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément EST-1 a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<NodeArgs eType="User" icon="7" nRep="81" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[JPetStore]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[ShoppingCart]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[EST-1.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["2"]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="85" >
<Disp><![CDATA[EST-1.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="84" >
<Disp><![CDATA[ShoppingCart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="83" >
<Disp><![CDATA[JPetStore]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj ><![CDATA[saisirElement]]></Obj>
<Details ><![CDATA[La chaîne '2' a été saisie.]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<NodeArgs eType="User" icon="7" nRep="86" status="Passed" >
<Disp><![CDATA[saisirElement]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj ><![CDATA[Verif visibilité Elément]]></Obj>
<Details ><![CDATA[L'élément Update Cart a été trouvé]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<NodeArgs eType="User" icon="7" nRep="87" status="Passed" >
<Disp><![CDATA[Verif visibilité Elément]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[JPetStore]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[ShoppingCart]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[Update Cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="91" >
<Disp><![CDATA[Update Cart.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="90" >
<Disp><![CDATA[ShoppingCart]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="89" >
<Disp><![CDATA[JPetStore]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj ><![CDATA[CliquerElement]]></Obj>
<Details ><![CDATA[L'élément a été cliqué.]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>
<TimeTick>1661414127</TimeTick>
<NodeArgs eType="User" icon="7" nRep="92" status="Passed" >
<Disp><![CDATA[CliquerElement]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj ><![CDATA[Prix non vérifé]]></Obj>
<Details ><![CDATA[Le prix n'est pas correct]]></Details>
<Time><![CDATA[25/08/2022 - 09:55:27]]></Time>