<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Paris, Madrid">
<General productName="Micro Focus UFT One" productVer="2021" os="Windows 10" host="NXQLX302"><DocLocation><![CDATA[C:\robot\test_UFT\JpetStore\JpetStore]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus UFT One"  >
<DName><![CDATA[JpetStore]]></DName>
<Res><![CDATA[Res49]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action principale]]></AName>
<Action rID="T5">
<AName><![CDATA[Affichage [Connexion]]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[25/08/2022 - 09:57:04]]></Time>
<TimeTick>1661414224</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Details>
<Time><![CDATA[25/08/2022 - 09:57:04]]></Time>
<TimeTick>1661414224</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Passed" Source="Affichage [Connexion]" SourceLine="21" >
<Disp><![CDATA[Run "C:\Program Files\Google\Chrome\Application\chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Passed" Source="Affichage [Connexion]" SourceLine="21" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[JPetStore]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[25/08/2022 - 09:57:24]]></Time>
<TimeTick>1661414244</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[JPetStore]]></Obj>
<Details plainTxt="False" ><![CDATA[Impossible&nbsp;d’identifier&nbsp;l’objet&nbsp;"JPetStore"&nbsp;(de&nbsp;classe&nbsp;Browser).<br/>Vérifiez&nbsp;que&nbsp;ces&nbsp;propriétés&nbsp;d’objet&nbsp;correspondent&nbsp;à&nbsp;un&nbsp;objet&nbsp;affiché&nbsp;dans&nbsp;l’application.]]></Details>
<Time><![CDATA[25/08/2022 - 09:57:24]]></Time>
<TimeTick>1661414244</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[JPetStore]]></Obj>
<Details plainTxt="False" ><![CDATA[Description physique de l’objet :<br>Mercury Class = Browser<br>CreationTime = 18<br>|Title = JPetStore Demo<br>openurl = https://petstore.octoperf.com/actions/Account.action?signonForm=<br>opentitle = JPetStore Demo<br>Opened By Testing Tool = 0<br>number of tabs = 20<br>Name = JPetStore Demo<br>]]></Details>
<Time><![CDATA[25/08/2022 - 09:57:24]]></Time>
<TimeTick>1661414244</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" status="Warning" nType="Description" >
<Disp><![CDATA[JPetStore]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="17" status="Failed" nType="Erreur d’exécution" >
<Disp><![CDATA[JPetStore]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" status="Failed" >
<Disp><![CDATA[JPetStore]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[JPetStore]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[25/08/2022 - 09:57:24]]></Time>
<TimeTick>1661414244</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Accueil]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[25/08/2022 - 09:57:24]]></Time>
<TimeTick>1661414244</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Erreur d’exécution]]></Obj>
<Details plainTxt="False" ><![CDATA[Impossible d’identifier l’objet &quot;JPetStore&quot; (de classe Browser).<BR/>Vérifiez que ces propriétés d’objet correspondent à un objet affiché dans l’application.<BR/>Fichier de fonction : C:\robot\test_UFT\JpetStore\Ressources\Library.qfl<BR/>Ligne (61) : &quot;		visibilite = Element.GetROProperty(&quot;visible&quot;)&quot;.]]></Details>
<Time><![CDATA[25/08/2022 - 09:57:24]]></Time>
<TimeTick>1661414244</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" status="Failed" Source="C:\robot\test_UFT\JpetStore\Ressources\Library.qfl" SourceLine="60" >
<Disp><![CDATA[Erreur d’exécution]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Arrêter l’exécution]]></Obj>
<Details plainTxt="False" ><![CDATA[Exécution arrêtée par l’utilisateur.]]></Details>
<Time><![CDATA[25/08/2022 - 09:57:29]]></Time>
<TimeTick>1661414249</TimeTick>
<NodeArgs eType="General" icon="10" nRep="22" status="Information" >
<Disp><![CDATA[Arrêter l’exécution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="20" status="Failed" Source="C:\robot\test_UFT\JpetStore\Ressources\Library.qfl" SourceLine="-1" >
<Disp><![CDATA[Accueil]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="19" status="Failed" Source="C:\robot\test_UFT\JpetStore\Ressources\Library.qfl" SourceLine="-1" >
<Disp><![CDATA[JPetStore]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/08/2022 - 09:57:04" eTime="25/08/2022 - 09:57:29" passed="1" failed="2" warnings="1" ><Param paramInOut = "In"><ParamName><![CDATA[browser]]></ParamName><ParamVal><![CDATA[chrome]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Failed" >
<Disp><![CDATA[Récapitulatif Affichage [Connexion]]]></Disp>
</NodeArgs>
</Action>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Arrêter l’exécution]]></Obj>
<Details plainTxt="False" ><![CDATA[Exécution arrêtée par l’utilisateur.]]></Details>
<Time><![CDATA[25/08/2022 - 09:57:29]]></Time>
<TimeTick>1661414249</TimeTick>
<NodeArgs eType="General" icon="10" nRep="24" status="Information" >
<Disp><![CDATA[Arrêter l’exécution]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25/08/2022 - 09:57:03" eTime="25/08/2022 - 09:57:29" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Récapitulatif Action principale]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Itération JpetStore 1 (ligne 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="25/08/2022 - 09:57:02" eTime="25/08/2022 - 09:57:29" passed="1" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Récapitulatif Test JpetStore]]></Disp>
</NodeArgs>
</Doc>
</Report>